version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  deploy:
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  test:
    jobs:
      - node/test
  test-and-deploy:
    jobs:
      - node/test
      - deploy:
        requires:
          - test
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
